<h1>
<?php
if (isset($_SESSION['action_result'])){
    echo $_SESSION['action_result'];
    unset($_SESSION['action_result']);
}
?>
</h1>
<form id="filter" method="post">
    <table>
        <tr>
            <td>
                <p>filter vacancies</p>
            </td>
            <td>
                language
            </td>
            <td>
                <select form="filter" name="<?php echo vacancies_data::$supported_languages['title'] ?>" <?php echo vacancies_data::$supported_languages['required'] ?>>
                    <option value="">default</option>
                    <?php
                    foreach (vacancies_data::$supported_languages['properties'] as $k => $y) {
                        if (isset($_POST[vacancies_data::$supported_languages['title']])) {
                            if ($_POST[vacancies_data::$supported_languages['title']] == $y) {
                                $selected = "selected";
                            } else {
                                $selected = "";
                            }
                        }
                        ?>               
                        <option <?php echo @$selected; ?> value="<?php echo $y ?>"><?php echo $k; ?></option>                
                        <?php
                    }
                    ?>
                </select>
            </td>
            <?php
            foreach ($list->properties as $v) {
                ?>
                <td><?php echo $v['title']; ?></td>
                <td>
                    <select form="filter" name="<?php echo $v['title'] ?>" <?php echo $v['multiple'];
            echo $v['required']; ?> >
                        <option value="">not specified</option>
                        <?php
                        foreach ($v['properties'] as $k => $y) {
                            if (isset($_POST[$v['title']])) {
                                if ($_POST[$v['title']] == $y) {
                                    $selected = "selected";
                                } else {
                                    $selected = "";
                                }
                            }
                            ?>               
                            <option <?php echo @$selected; ?> value="<?php echo $y; ?>"><?php echo $k; ?></option>                
                            <?php
                        }
                        ?>
                    </select>
                </td>
                <?php
            }
            ?>
            <td>
                <input type="submit" value="show">
            </td>
        </tr>
    </table>
</form>

<table>
    <tr>
        <td>
        <form id="add" method="post">
            <button form="add" formaction="/admin/vacancies/add">Add new vacancy</button>
        </form>
        </td>
    </tr>
<?php
for ($i = 0; $i < count($output_array); $i++) {
    ?>

    <tr>
        <td>
            <h2><?php echo $output_array[$i][2]; ?></h2>
        </td>
        <td>
            <form id="admin_tools" method="post">
                <button form = "admin_tools" name="update" formaction="/admin/vacancies/update" value="<?php echo $output_array[$i][0]; ?>">update</button>
            
                <button form = "admin_tools" name="delete" formaction="/admin/vacancies/delete" value="<?php echo $output_array[$i][0]; ?>">delete</button>
                             
            </form>
        </td>
    </tr>
    <tr>
        <td>
            <p>vacancy id: <?php echo $output_array[$i][0]; ?></p>
        </td>
        <td>
            <p>department: <?php echo array_search($output_array[$i]['dpt_id'], departments_data::$supported_departments['properties']); ?></p>
        </td>
    </tr>
    <tr>
        <td>
            <p>description:<br><?php echo $output_array[$i][3]; ?></p>
        </td>
    </tr>
    <tr>
        <td>
    <hr>
        </td>
    </tr>
    <?php
}
?>
</table>