<h1>
    <?php
    if (isset($_SESSION['action_result'])) {
        echo $_SESSION['action_result'];
        unset($_SESSION['action_result']);
    }
    ?>
</h1>
<form id="vacancies_add" method="post">
    <table>
        <tr>
            <td>
                ID: <?php echo $updater->item_id; ?>
            </td>
        </tr>
        <tr>
            <td>
                Department
            </td>
            <td>
                <select form="vacancies_add" name="<?php echo departments_data::$supported_departments['title']; ?>">        
                    <?php
                    foreach (departments_data::$supported_departments['properties'] as $k => $v) {
                        if ($output_array[0]['dpt_id'] == $v) {
                            $selected = "selected";
                        } else {
                            $selected = "";
                        }
                        echo "<option " . $selected . " value=\"" . $v . "\">" . $k . "</option>";
                    }
                    ?>               
                </select>
            </td>
            <td><?php echo @$errors[departments_data::$supported_departments['title']] ?></td>
        </tr>
        <?php
                    
        foreach (vacancies_data::$supported_languages['properties'] as $k => $y) {
            ?>
        <tr>
            <td>
                <?php echo "language: ".$k ?>
            </td>
        </tr>
        <tr>
            <td>
                Title
            </td>
            <td>
                <input type="text" name="title_<?php echo $y; ?>" value="<?php echo $output_array[0]['title_'.$y] ?>" >
            </td>
            <td><?php echo @$errors['title_'.$y] ?></td>
        </tr>
        <tr>
            <td>
                Description
            </td>
            <td>
                <textarea name="description_<?php echo $y; ?>" ><?php echo $output_array[0]['description_'.$y]; ?></textarea>
            </td>
        </tr>
        
        <?php
        }
        ?>
        
              
        <tr>
            <td>
                <input type="submit" name="update_vacancy" value="update" >
            </td>
        </tr>
    </table>

</form>