<div class="submenu">
<form id="filter" method="post">
    <table>
        <tr>
            <td>
                <p><span>filter vacancies</span></p>
            </td>
            <td>
                <p>
                language
                </p>
            </td>
            <td>
                <select form="filter" name="<?php echo vacancies_data::$supported_languages['title'] ?>" <?php echo vacancies_data::$supported_languages['required'] ?>>
                    <option value="">default</option>
                    <?php
                    foreach (vacancies_data::$supported_languages['properties'] as $k => $y) {
                        if (isset($_POST[vacancies_data::$supported_languages['title']])) {
                            if ($_POST[vacancies_data::$supported_languages['title']] == $y) {
                                $selected = "selected";
                            } else {
                                $selected = "";
                            }
                        }
                        ?>               
                        <option <?php echo @$selected; ?> value="<?php echo $y ?>"><?php echo $k; ?></option>                
                        <?php
                    }
                    ?>
                </select>
            </td>
            <?php
            foreach ($list->properties as $v) {
                ?>
            <td><p><?php echo $v['title']; ?></p></td>
                <td>
                    <select form="filter" name="<?php echo $v['title'] ?>" <?php echo $v['multiple'];
            echo $v['required']; ?> >
                        <option value="">not specified</option>
                        <?php
                        foreach ($v['properties'] as $k => $y) {
                            if (isset($_POST[$v['title']])) {
                                if ($_POST[$v['title']] == $y) {
                                    $selected = "selected";
                                } else {
                                    $selected = "";
                                }
                            }
                            ?>               
                            <option <?php echo @$selected; ?> value="<?php echo $y; ?>"><?php echo $k; ?></option>                
                            <?php
                        }
                        ?>
                    </select>
                </td>
                <?php
            }
            ?>
            <td>
                <input type="submit" value="show">
            </td>
        </tr>
    </table>
</form>
</div>
<div class="reset"></div>

<div class="container_3">

<?php
for ($i = 0; $i < count($output_array); $i++) {
    ?>
    <div class="grid_3">
        <h2><?php echo $output_array[$i][2]; ?></h2>
        <p>vacancy id: <?php echo $output_array[$i][0]; ?></p>
        <p>department: <?php echo array_search($output_array[$i]['dpt_id'], departments_data::$supported_departments['properties']); ?></p>
        <p>description:<br><?php echo $output_array[$i][3]; ?></p>
        <hr>
    </div>
    

    <?php
}
?>
    
    
</div>
<div class="reset"></div>
