<!DOCTYPE html>
<html>
    <head>
        <title>Блочная верстка</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="/css/global.css">
    </head>
    <body>
        <p>MENU</p>
        <div>
            <a href="/vacancies/show">Vacancies</a>
        </div>
        <div>
            <a href="admin/vacancies/select">Admin</a>
        </div>
        <?php
        include_once router::if_exists(__DIR__ . '/../../module/' . $_GET['module'] . '/view/' . $_GET['page'] . '.phtml');
        ?>

    </body>