<?php
use \module\vacancies\libs;
use \module\vacancies\config;


if (isset($_SESSION['action_result'])){
    ?>
<div class="submenu">
    <span>
<?php
    echo $_SESSION['action_result'];
    unset($_SESSION['action_result']);
    ?>
    </span>
</div>
<?php
    }
    ?>
<div class="reset"></div>

<div class="submenu">

<form id="vacancies_add" method="post">
    <input type="hidden" name="update" value="<?php echo $updater->item_id; ?>">
    <table>
        <tr>
            <td>
                <p>ID: <?php echo $updater->item_id; ?></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>Department</p>
            </td>
            <td>
                <select form="vacancies_add" name="<?php echo config\departments_data::$supported_departments['title']; ?>">        
                    <?php
                    foreach (config\departments_data::$supported_departments['properties'] as $k => $v) {
                        if ($output_array[0]['dpt_id'] == $v) {
                            $selected = "selected";
                        } else {
                            $selected = "";
                        }
                        echo "<option " . $selected . " value=\"" . $v . "\">" . $k . "</option>";
                    }
                    ?>               
                </select>
            </td>
            <td><?php echo @$errors[config\departments_data::$supported_departments['title']] ?></td>
        </tr>
        <?php
                    
        foreach (config\vacancies_data::$supported_languages['properties'] as $k => $y) {
            ?>
        <tr>
            <td>
                <p><?php echo "language: ".$k ?></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>Title</p>
            </td>
            <td>
                <input type="text" name="title_<?php echo $y; ?>" value="<?php echo $output_array[0]['title_'.$y] ?>" >
            </td>
            <td><?php echo @$errors['title_'.$y] ?></td>
        </tr>
        <tr>
            <td>
                <p>Description</p>
            </td>
            <td>
                <textarea name="description_<?php echo $y; ?>" ><?php echo $output_array[0]['description_'.$y]; ?></textarea>
            </td>
        </tr>
        
        <?php
        }
        ?>
        
              
        <tr>
            <td>
                <input type="submit" name="update_vacancy" value="update" >
            </td>
        </tr>
    </table>

</form>
</div>
<div class="reset"></div>